### ISSUE TITLE
[+] Doesn't list all objects

### ISSUE THREAD

**Issue by Azathothas** [cmj2002/r2-dir-list#1]
Hi, thank you so much for this.

I have deployed this on https://bin.ajam.dev however it's not listing all objects from the bucket.
For example: 
```bash
❯ curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/METADATA.json" | jq -r '.[].Name' | sort -u | wc -l
601

❯ curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/METADATA.json" | jq -r '.[].Name' | sort -u | tail -n 5
zenith
zfxtop
zgrab2
zoxide
zstd
```
Whereas, it's being truncated here: https://bin.ajam.dev/x86_64_Linux/
![image](https://github.com/cmj2002/r2-dir-list/assets/58171889/02b1de84-a301-4024-a3cf-f82ef54715c4)

This is only the 572nd entry:  https://bin.ajam.dev/x86_64_Linux/METADATA.json
![image](https://github.com/cmj2002/r2-dir-list/assets/58171889/2c0b3b01-3b88-400a-93d7-cc8bd6ad26f5)

I don't know `TS/JS`, but is this line any relevant:
https://github.com/cmj2002/r2-dir-list/blob/de8fbbaf9d312dc594888062629b1ac4ccffd36b/src/index.ts#L24
```typescript
        const index = await bucket.list({
            // TODO: Should manage limit here, but since I won't have more than 1000 files in a single folder, I just ignore it
            prefix: objectKey,
            delimiter: '/',
            include: ['httpMetadata', 'customMetadata']
        });
```

**Comment by cmj2002** [comment]
Try to deploy branch `manage-limit`, it may solve the problem. If it works, I will merge it into main branch.

**Comment by Azathothas** [comment]
@cmj2002 Yes it works, thank you again.

I have deployed with the [new index.ts](https://github.com/cmj2002/r2-dir-list/blob/manage-limit/src/index.ts) at : https://github.com/Azathothas/bin.ajam.dev

https://bin.ajam.dev/x86_64_Linux/
![image](https://github.com/cmj2002/r2-dir-list/assets/58171889/f62c611b-9f91-4186-8a83-1ca8bc23c210)
